/*
 * Docker Engine API
 *
 * The Engine API is an HTTP API served by Docker Engine. It is the API the Docker client uses to communicate with the Engine, so everything the Docker client can do can be done with the API.  Most of the client's commands map directly to API endpoints (e.g. `docker ps` is `GET /containers/json`). The notable exception is running containers, which consists of several API calls.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```  # Versioning  The API is usually changed in each release, so API calls are versioned to ensure that clients don't break. To lock to a specific version of the API, you prefix the URL with its version, for example, call `/v1.30/info` to use the v1.30 version of the `/info` endpoint. If the API version specified in the URL is not supported by the daemon, a HTTP `400 Bad Request` error message is returned.  If you omit the version-prefix, the current version of the API (v1.41) is used. For example, calling `/info` is the same as calling `/v1.41/info`. Using the API without a version-prefix is deprecated and will be removed in a future release.  Engine releases in the near future should support this version of the API, so your client will continue to work even if it is talking to a newer Engine.  The API uses an open schema model, which means server may add extra properties to responses. Likewise, the server will ignore any extra query parameters and request body properties. When you write clients, you need to ignore additional properties in responses to ensure they do not break when talking to newer daemons.   # Authentication  Authentication for registries is handled client side. The client has to send authentication details to various endpoints that need to communicate with registries, such as `POST /images/(name)/push`. These are sent as `X-Registry-Auth` header as a [base64url encoded](https://tools.ietf.org/html/rfc4648#section-5) (JSON) string with the following structure:  ``` {   \"username\": \"string\",   \"password\": \"string\",   \"email\": \"string\",   \"serveraddress\": \"string\" } ```  The `serveraddress` is a domain/IP without a protocol. Throughout this structure, double quotes are required.  If you have already got an identity token from the [`/auth` endpoint](#operation/SystemAuth), you can just pass this instead of credentials:  ``` {   \"identitytoken\": \"9cbaf023786cd7...\" } ``` 
 *
 * API version: 1.41
 * Generated by: api Generator (https://api-generator.tech)
 */

package api

import (
	"context"
	"net/http"
	"os"
)



// ConfigApiRouter defines the required methods for binding the api requests to a responses for the ConfigApi
// The ConfigApiRouter implementation should parse necessary information from the http request, 
// pass the data to a ConfigApiServicer to perform the required actions, then write the service results to the http response.
type ConfigApiRouter interface { 
	ConfigCreate(http.ResponseWriter, *http.Request)
	ConfigDelete(http.ResponseWriter, *http.Request)
	ConfigInspect(http.ResponseWriter, *http.Request)
	ConfigList(http.ResponseWriter, *http.Request)
	ConfigUpdate(http.ResponseWriter, *http.Request)
}
// ContainerApiRouter defines the required methods for binding the api requests to a responses for the ContainerApi
// The ContainerApiRouter implementation should parse necessary information from the http request, 
// pass the data to a ContainerApiServicer to perform the required actions, then write the service results to the http response.
type ContainerApiRouter interface { 
	ContainerArchive(http.ResponseWriter, *http.Request)
	ContainerArchiveInfo(http.ResponseWriter, *http.Request)
	ContainerAttach(http.ResponseWriter, *http.Request)
	ContainerAttachWebsocket(http.ResponseWriter, *http.Request)
	ContainerChanges(http.ResponseWriter, *http.Request)
	ContainerCreate(http.ResponseWriter, *http.Request)
	ContainerDelete(http.ResponseWriter, *http.Request)
	ContainerExport(http.ResponseWriter, *http.Request)
	ContainerInspect(http.ResponseWriter, *http.Request)
	ContainerKill(http.ResponseWriter, *http.Request)
	ContainerList(http.ResponseWriter, *http.Request)
	ContainerLogs(http.ResponseWriter, *http.Request)
	ContainerPause(http.ResponseWriter, *http.Request)
	ContainerPrune(http.ResponseWriter, *http.Request)
	ContainerRename(http.ResponseWriter, *http.Request)
	ContainerResize(http.ResponseWriter, *http.Request)
	ContainerRestart(http.ResponseWriter, *http.Request)
	ContainerStart(http.ResponseWriter, *http.Request)
	ContainerStats(http.ResponseWriter, *http.Request)
	ContainerStop(http.ResponseWriter, *http.Request)
	ContainerTop(http.ResponseWriter, *http.Request)
	ContainerUnpause(http.ResponseWriter, *http.Request)
	ContainerUpdate(http.ResponseWriter, *http.Request)
	ContainerWait(http.ResponseWriter, *http.Request)
	PutContainerArchive(http.ResponseWriter, *http.Request)
}
// DistributionApiRouter defines the required methods for binding the api requests to a responses for the DistributionApi
// The DistributionApiRouter implementation should parse necessary information from the http request, 
// pass the data to a DistributionApiServicer to perform the required actions, then write the service results to the http response.
type DistributionApiRouter interface { 
	DistributionInspect(http.ResponseWriter, *http.Request)
}
// ExecApiRouter defines the required methods for binding the api requests to a responses for the ExecApi
// The ExecApiRouter implementation should parse necessary information from the http request, 
// pass the data to a ExecApiServicer to perform the required actions, then write the service results to the http response.
type ExecApiRouter interface { 
	ContainerExec(http.ResponseWriter, *http.Request)
	ExecInspect(http.ResponseWriter, *http.Request)
	ExecResize(http.ResponseWriter, *http.Request)
	ExecStart(http.ResponseWriter, *http.Request)
}
// ImageApiRouter defines the required methods for binding the api requests to a responses for the ImageApi
// The ImageApiRouter implementation should parse necessary information from the http request, 
// pass the data to a ImageApiServicer to perform the required actions, then write the service results to the http response.
type ImageApiRouter interface { 
	BuildPrune(http.ResponseWriter, *http.Request)
	ImageBuild(http.ResponseWriter, *http.Request)
	ImageCommit(http.ResponseWriter, *http.Request)
	ImageCreate(http.ResponseWriter, *http.Request)
	ImageDelete(http.ResponseWriter, *http.Request)
	ImageGet(http.ResponseWriter, *http.Request)
	ImageGetAll(http.ResponseWriter, *http.Request)
	ImageHistory(http.ResponseWriter, *http.Request)
	ImageInspect(http.ResponseWriter, *http.Request)
	ImageList(http.ResponseWriter, *http.Request)
	ImageLoad(http.ResponseWriter, *http.Request)
	ImagePrune(http.ResponseWriter, *http.Request)
	ImagePush(http.ResponseWriter, *http.Request)
	ImageSearch(http.ResponseWriter, *http.Request)
	ImageTag(http.ResponseWriter, *http.Request)
}
// NetworkApiRouter defines the required methods for binding the api requests to a responses for the NetworkApi
// The NetworkApiRouter implementation should parse necessary information from the http request, 
// pass the data to a NetworkApiServicer to perform the required actions, then write the service results to the http response.
type NetworkApiRouter interface { 
	NetworkConnect(http.ResponseWriter, *http.Request)
	NetworkCreate(http.ResponseWriter, *http.Request)
	NetworkDelete(http.ResponseWriter, *http.Request)
	NetworkDisconnect(http.ResponseWriter, *http.Request)
	NetworkInspect(http.ResponseWriter, *http.Request)
	NetworkList(http.ResponseWriter, *http.Request)
	NetworkPrune(http.ResponseWriter, *http.Request)
}
// NodeApiRouter defines the required methods for binding the api requests to a responses for the NodeApi
// The NodeApiRouter implementation should parse necessary information from the http request, 
// pass the data to a NodeApiServicer to perform the required actions, then write the service results to the http response.
type NodeApiRouter interface { 
	NodeDelete(http.ResponseWriter, *http.Request)
	NodeInspect(http.ResponseWriter, *http.Request)
	NodeList(http.ResponseWriter, *http.Request)
	NodeUpdate(http.ResponseWriter, *http.Request)
}
// PluginApiRouter defines the required methods for binding the api requests to a responses for the PluginApi
// The PluginApiRouter implementation should parse necessary information from the http request, 
// pass the data to a PluginApiServicer to perform the required actions, then write the service results to the http response.
type PluginApiRouter interface { 
	GetPluginPrivileges(http.ResponseWriter, *http.Request)
	PluginCreate(http.ResponseWriter, *http.Request)
	PluginDelete(http.ResponseWriter, *http.Request)
	PluginDisable(http.ResponseWriter, *http.Request)
	PluginEnable(http.ResponseWriter, *http.Request)
	PluginInspect(http.ResponseWriter, *http.Request)
	PluginList(http.ResponseWriter, *http.Request)
	PluginPull(http.ResponseWriter, *http.Request)
	PluginPush(http.ResponseWriter, *http.Request)
	PluginSet(http.ResponseWriter, *http.Request)
	PluginUpgrade(http.ResponseWriter, *http.Request)
}
// SecretApiRouter defines the required methods for binding the api requests to a responses for the SecretApi
// The SecretApiRouter implementation should parse necessary information from the http request, 
// pass the data to a SecretApiServicer to perform the required actions, then write the service results to the http response.
type SecretApiRouter interface { 
	SecretCreate(http.ResponseWriter, *http.Request)
	SecretDelete(http.ResponseWriter, *http.Request)
	SecretInspect(http.ResponseWriter, *http.Request)
	SecretList(http.ResponseWriter, *http.Request)
	SecretUpdate(http.ResponseWriter, *http.Request)
}
// ServiceApiRouter defines the required methods for binding the api requests to a responses for the ServiceApi
// The ServiceApiRouter implementation should parse necessary information from the http request, 
// pass the data to a ServiceApiServicer to perform the required actions, then write the service results to the http response.
type ServiceApiRouter interface { 
	ServiceCreate(http.ResponseWriter, *http.Request)
	ServiceDelete(http.ResponseWriter, *http.Request)
	ServiceInspect(http.ResponseWriter, *http.Request)
	ServiceList(http.ResponseWriter, *http.Request)
	ServiceLogs(http.ResponseWriter, *http.Request)
	ServiceUpdate(http.ResponseWriter, *http.Request)
}
// SessionApiRouter defines the required methods for binding the api requests to a responses for the SessionApi
// The SessionApiRouter implementation should parse necessary information from the http request, 
// pass the data to a SessionApiServicer to perform the required actions, then write the service results to the http response.
type SessionApiRouter interface { 
	Session(http.ResponseWriter, *http.Request)
}
// SwarmApiRouter defines the required methods for binding the api requests to a responses for the SwarmApi
// The SwarmApiRouter implementation should parse necessary information from the http request, 
// pass the data to a SwarmApiServicer to perform the required actions, then write the service results to the http response.
type SwarmApiRouter interface { 
	SwarmInit(http.ResponseWriter, *http.Request)
	SwarmInspect(http.ResponseWriter, *http.Request)
	SwarmJoin(http.ResponseWriter, *http.Request)
	SwarmLeave(http.ResponseWriter, *http.Request)
	SwarmUnlock(http.ResponseWriter, *http.Request)
	SwarmUnlockkey(http.ResponseWriter, *http.Request)
	SwarmUpdate(http.ResponseWriter, *http.Request)
}
// SystemApiRouter defines the required methods for binding the api requests to a responses for the SystemApi
// The SystemApiRouter implementation should parse necessary information from the http request, 
// pass the data to a SystemApiServicer to perform the required actions, then write the service results to the http response.
type SystemApiRouter interface { 
	SystemAuth(http.ResponseWriter, *http.Request)
	SystemDataUsage(http.ResponseWriter, *http.Request)
	SystemEvents(http.ResponseWriter, *http.Request)
	SystemInfo(http.ResponseWriter, *http.Request)
	SystemPing(http.ResponseWriter, *http.Request)
	SystemPingHead(http.ResponseWriter, *http.Request)
	SystemVersion(http.ResponseWriter, *http.Request)
}
// TaskApiRouter defines the required methods for binding the api requests to a responses for the TaskApi
// The TaskApiRouter implementation should parse necessary information from the http request, 
// pass the data to a TaskApiServicer to perform the required actions, then write the service results to the http response.
type TaskApiRouter interface { 
	TaskInspect(http.ResponseWriter, *http.Request)
	TaskList(http.ResponseWriter, *http.Request)
	TaskLogs(http.ResponseWriter, *http.Request)
}
// VolumeApiRouter defines the required methods for binding the api requests to a responses for the VolumeApi
// The VolumeApiRouter implementation should parse necessary information from the http request, 
// pass the data to a VolumeApiServicer to perform the required actions, then write the service results to the http response.
type VolumeApiRouter interface { 
	VolumeCreate(http.ResponseWriter, *http.Request)
	VolumeDelete(http.ResponseWriter, *http.Request)
	VolumeInspect(http.ResponseWriter, *http.Request)
	VolumeList(http.ResponseWriter, *http.Request)
	VolumePrune(http.ResponseWriter, *http.Request)
}


// ConfigApiServicer defines the api actions for the ConfigApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type ConfigApiServicer interface { 
	ConfigCreate(context.Context, UNKNOWN_BASE_TYPE) (ImplResponse, error)
	ConfigDelete(context.Context, string) (ImplResponse, error)
	ConfigInspect(context.Context, string) (ImplResponse, error)
	ConfigList(context.Context, string) (ImplResponse, error)
	ConfigUpdate(context.Context, string, int64, ConfigSpec) (ImplResponse, error)
}


// ContainerApiServicer defines the api actions for the ContainerApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type ContainerApiServicer interface { 
	ContainerArchive(context.Context, string, string) (ImplResponse, error)
	ContainerArchiveInfo(context.Context, string, string) (ImplResponse, error)
	ContainerAttach(context.Context, string, string, bool, bool, bool, bool, bool) (ImplResponse, error)
	ContainerAttachWebsocket(context.Context, string, string, bool, bool, bool, bool, bool) (ImplResponse, error)
	ContainerChanges(context.Context, string) (ImplResponse, error)
	ContainerCreate(context.Context, UNKNOWN_BASE_TYPE, string) (ImplResponse, error)
	ContainerDelete(context.Context, string, bool, bool, bool) (ImplResponse, error)
	ContainerExport(context.Context, string) (ImplResponse, error)
	ContainerInspect(context.Context, string, bool) (ImplResponse, error)
	ContainerKill(context.Context, string, string) (ImplResponse, error)
	ContainerList(context.Context, bool, int32, bool, string) (ImplResponse, error)
	ContainerLogs(context.Context, string, bool, bool, bool, int32, int32, bool, string) (ImplResponse, error)
	ContainerPause(context.Context, string) (ImplResponse, error)
	ContainerPrune(context.Context, string) (ImplResponse, error)
	ContainerRename(context.Context, string, string) (ImplResponse, error)
	ContainerResize(context.Context, string, int32, int32) (ImplResponse, error)
	ContainerRestart(context.Context, string, int32) (ImplResponse, error)
	ContainerStart(context.Context, string, string) (ImplResponse, error)
	ContainerStats(context.Context, string, bool, bool) (ImplResponse, error)
	ContainerStop(context.Context, string, int32) (ImplResponse, error)
	ContainerTop(context.Context, string, string) (ImplResponse, error)
	ContainerUnpause(context.Context, string) (ImplResponse, error)
	ContainerUpdate(context.Context, string, UNKNOWN_BASE_TYPE) (ImplResponse, error)
	ContainerWait(context.Context, string, string) (ImplResponse, error)
	PutContainerArchive(context.Context, string, string, *os.File, string, string) (ImplResponse, error)
}


// DistributionApiServicer defines the api actions for the DistributionApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type DistributionApiServicer interface { 
	DistributionInspect(context.Context, string) (ImplResponse, error)
}


// ExecApiServicer defines the api actions for the ExecApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type ExecApiServicer interface { 
	ContainerExec(context.Context, string, InlineObject) (ImplResponse, error)
	ExecInspect(context.Context, string) (ImplResponse, error)
	ExecResize(context.Context, string, int32, int32) (ImplResponse, error)
	ExecStart(context.Context, string, InlineObject1) (ImplResponse, error)
}


// ImageApiServicer defines the api actions for the ImageApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type ImageApiServicer interface { 
	BuildPrune(context.Context, int64, bool, string) (ImplResponse, error)
	ImageBuild(context.Context, string, string, string, string, bool, bool, string, string, bool, bool, int32, int32, int32, string, int32, int32, string, int32, bool, string, string, string, string, string, string, string, *os.File) (ImplResponse, error)
	ImageCommit(context.Context, string, string, string, string, string, bool, string, ContainerConfig) (ImplResponse, error)
	ImageCreate(context.Context, string, string, string, string, string, string, string, string) (ImplResponse, error)
	ImageDelete(context.Context, string, bool, bool) (ImplResponse, error)
	ImageGet(context.Context, string) (ImplResponse, error)
	ImageGetAll(context.Context, []string) (ImplResponse, error)
	ImageHistory(context.Context, string) (ImplResponse, error)
	ImageInspect(context.Context, string) (ImplResponse, error)
	ImageList(context.Context, bool, string, bool) (ImplResponse, error)
	ImageLoad(context.Context, bool, *os.File) (ImplResponse, error)
	ImagePrune(context.Context, string) (ImplResponse, error)
	ImagePush(context.Context, string, string, string) (ImplResponse, error)
	ImageSearch(context.Context, string, int32, string) (ImplResponse, error)
	ImageTag(context.Context, string, string, string) (ImplResponse, error)
}


// NetworkApiServicer defines the api actions for the NetworkApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type NetworkApiServicer interface { 
	NetworkConnect(context.Context, string, InlineObject3) (ImplResponse, error)
	NetworkCreate(context.Context, InlineObject2) (ImplResponse, error)
	NetworkDelete(context.Context, string) (ImplResponse, error)
	NetworkDisconnect(context.Context, string, InlineObject4) (ImplResponse, error)
	NetworkInspect(context.Context, string, bool, string) (ImplResponse, error)
	NetworkList(context.Context, string) (ImplResponse, error)
	NetworkPrune(context.Context, string) (ImplResponse, error)
}


// NodeApiServicer defines the api actions for the NodeApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type NodeApiServicer interface { 
	NodeDelete(context.Context, string, bool) (ImplResponse, error)
	NodeInspect(context.Context, string) (ImplResponse, error)
	NodeList(context.Context, string) (ImplResponse, error)
	NodeUpdate(context.Context, string, int64, NodeSpec) (ImplResponse, error)
}


// PluginApiServicer defines the api actions for the PluginApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type PluginApiServicer interface { 
	GetPluginPrivileges(context.Context, string) (ImplResponse, error)
	PluginCreate(context.Context, string, *os.File) (ImplResponse, error)
	PluginDelete(context.Context, string, bool) (ImplResponse, error)
	PluginDisable(context.Context, string) (ImplResponse, error)
	PluginEnable(context.Context, string, int32) (ImplResponse, error)
	PluginInspect(context.Context, string) (ImplResponse, error)
	PluginList(context.Context, string) (ImplResponse, error)
	PluginPull(context.Context, string, string, string, []InlineObject) (ImplResponse, error)
	PluginPush(context.Context, string) (ImplResponse, error)
	PluginSet(context.Context, string, []string) (ImplResponse, error)
	PluginUpgrade(context.Context, string, string, string, []InlineObject) (ImplResponse, error)
}


// SecretApiServicer defines the api actions for the SecretApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type SecretApiServicer interface { 
	SecretCreate(context.Context, UNKNOWN_BASE_TYPE) (ImplResponse, error)
	SecretDelete(context.Context, string) (ImplResponse, error)
	SecretInspect(context.Context, string) (ImplResponse, error)
	SecretList(context.Context, string) (ImplResponse, error)
	SecretUpdate(context.Context, string, int64, SecretSpec) (ImplResponse, error)
}


// ServiceApiServicer defines the api actions for the ServiceApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type ServiceApiServicer interface { 
	ServiceCreate(context.Context, UNKNOWN_BASE_TYPE, string) (ImplResponse, error)
	ServiceDelete(context.Context, string) (ImplResponse, error)
	ServiceInspect(context.Context, string, bool) (ImplResponse, error)
	ServiceList(context.Context, string, bool) (ImplResponse, error)
	ServiceLogs(context.Context, string, bool, bool, bool, bool, int32, bool, string) (ImplResponse, error)
	ServiceUpdate(context.Context, string, int32, UNKNOWN_BASE_TYPE, string, string, string) (ImplResponse, error)
}


// SessionApiServicer defines the api actions for the SessionApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type SessionApiServicer interface { 
	Session(context.Context) (ImplResponse, error)
}


// SwarmApiServicer defines the api actions for the SwarmApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type SwarmApiServicer interface { 
	SwarmInit(context.Context, InlineObject5) (ImplResponse, error)
	SwarmInspect(context.Context) (ImplResponse, error)
	SwarmJoin(context.Context, InlineObject6) (ImplResponse, error)
	SwarmLeave(context.Context, bool) (ImplResponse, error)
	SwarmUnlock(context.Context, InlineObject7) (ImplResponse, error)
	SwarmUnlockkey(context.Context) (ImplResponse, error)
	SwarmUpdate(context.Context, int64, SwarmSpec, bool, bool, bool) (ImplResponse, error)
}


// SystemApiServicer defines the api actions for the SystemApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type SystemApiServicer interface { 
	SystemAuth(context.Context, AuthConfig) (ImplResponse, error)
	SystemDataUsage(context.Context) (ImplResponse, error)
	SystemEvents(context.Context, string, string, string) (ImplResponse, error)
	SystemInfo(context.Context) (ImplResponse, error)
	SystemPing(context.Context) (ImplResponse, error)
	SystemPingHead(context.Context) (ImplResponse, error)
	SystemVersion(context.Context) (ImplResponse, error)
}


// TaskApiServicer defines the api actions for the TaskApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type TaskApiServicer interface { 
	TaskInspect(context.Context, string) (ImplResponse, error)
	TaskList(context.Context, string) (ImplResponse, error)
	TaskLogs(context.Context, string, bool, bool, bool, bool, int32, bool, string) (ImplResponse, error)
}


// VolumeApiServicer defines the api actions for the VolumeApi service
// This interface intended to stay up to date with the api yaml used to generate it, 
// while the service implementation can ignored with the .api-generator-ignore file 
// and updated with the logic required for the API.
type VolumeApiServicer interface { 
	VolumeCreate(context.Context, VolumeConfig) (ImplResponse, error)
	VolumeDelete(context.Context, string, bool) (ImplResponse, error)
	VolumeInspect(context.Context, string) (ImplResponse, error)
	VolumeList(context.Context, string) (ImplResponse, error)
	VolumePrune(context.Context, string) (ImplResponse, error)
}
