/*
 * Docker Engine API
 *
 * The Engine API is an HTTP API served by Docker Engine. It is the API the Docker client uses to communicate with the Engine, so everything the Docker client can do can be done with the API.  Most of the client's commands map directly to API endpoints (e.g. `docker ps` is `GET /containers/json`). The notable exception is running containers, which consists of several API calls.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```  # Versioning  The API is usually changed in each release, so API calls are versioned to ensure that clients don't break. To lock to a specific version of the API, you prefix the URL with its version, for example, call `/v1.30/info` to use the v1.30 version of the `/info` endpoint. If the API version specified in the URL is not supported by the daemon, a HTTP `400 Bad Request` error message is returned.  If you omit the version-prefix, the current version of the API (v1.41) is used. For example, calling `/info` is the same as calling `/v1.41/info`. Using the API without a version-prefix is deprecated and will be removed in a future release.  Engine releases in the near future should support this version of the API, so your client will continue to work even if it is talking to a newer Engine.  The API uses an open schema model, which means server may add extra properties to responses. Likewise, the server will ignore any extra query parameters and request body properties. When you write clients, you need to ignore additional properties in responses to ensure they do not break when talking to newer daemons.   # Authentication  Authentication for registries is handled client side. The client has to send authentication details to various endpoints that need to communicate with registries, such as `POST /images/(name)/push`. These are sent as `X-Registry-Auth` header as a [base64url encoded](https://tools.ietf.org/html/rfc4648#section-5) (JSON) string with the following structure:  ``` {   \"username\": \"string\",   \"password\": \"string\",   \"email\": \"string\",   \"serveraddress\": \"string\" } ```  The `serveraddress` is a domain/IP without a protocol. Throughout this structure, double quotes are required.  If you have already got an identity token from the [`/auth` endpoint](#operation/SystemAuth), you can just pass this instead of credentials:  ``` {   \"identitytoken\": \"9cbaf023786cd7...\" } ``` 
 *
 * API version: 1.41
 * Generated by: api Generator (https://api-generator.tech)
 */

package api

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A ImageApiController binds http requests to an api service and writes the service results to the http response
type ImageApiController struct {
	service ImageApiServicer
}

// NewImageApiController creates a default api controller
func NewImageApiController(s ImageApiServicer) Router {
	return &ImageApiController{ service: s }
}

// Routes returns all of the api route for the ImageApiController
func (c *ImageApiController) Routes() Routes {
	return Routes{ 
		{
			"BuildPrune",
			strings.ToUpper("Post"),
			"/v1.41/build/prune",
			c.BuildPrune,
		},
		{
			"ImageBuild",
			strings.ToUpper("Post"),
			"/v1.41/build",
			c.ImageBuild,
		},
		{
			"ImageCommit",
			strings.ToUpper("Post"),
			"/v1.41/commit",
			c.ImageCommit,
		},
		{
			"ImageCreate",
			strings.ToUpper("Post"),
			"/v1.41/images/create",
			c.ImageCreate,
		},
		{
			"ImageDelete",
			strings.ToUpper("Delete"),
			"/v1.41/images/{name}",
			c.ImageDelete,
		},
		{
			"ImageGet",
			strings.ToUpper("Get"),
			"/v1.41/images/{name}/get",
			c.ImageGet,
		},
		{
			"ImageGetAll",
			strings.ToUpper("Get"),
			"/v1.41/images/get",
			c.ImageGetAll,
		},
		{
			"ImageHistory",
			strings.ToUpper("Get"),
			"/v1.41/images/{name}/history",
			c.ImageHistory,
		},
		{
			"ImageInspect",
			strings.ToUpper("Get"),
			"/v1.41/images/{name}/json",
			c.ImageInspect,
		},
		{
			"ImageList",
			strings.ToUpper("Get"),
			"/v1.41/images/json",
			c.ImageList,
		},
		{
			"ImageLoad",
			strings.ToUpper("Post"),
			"/v1.41/images/load",
			c.ImageLoad,
		},
		{
			"ImagePrune",
			strings.ToUpper("Post"),
			"/v1.41/images/prune",
			c.ImagePrune,
		},
		{
			"ImagePush",
			strings.ToUpper("Post"),
			"/v1.41/images/{name}/push",
			c.ImagePush,
		},
		{
			"ImageSearch",
			strings.ToUpper("Get"),
			"/v1.41/images/search",
			c.ImageSearch,
		},
		{
			"ImageTag",
			strings.ToUpper("Post"),
			"/v1.41/images/{name}/tag",
			c.ImageTag,
		},
	}
}

// BuildPrune - Delete builder cache
func (c *ImageApiController) BuildPrune(w http.ResponseWriter, r *http.Request) { 
	query := r.URL.Query()
	keepStorage, err := parseInt64Parameter(query.Get("keep-storage"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	all := query.Get("all")
	filters := query.Get("filters")
	result, err := c.service.BuildPrune(r.Context(), keepStorage, all, filters)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ImageBuild - Build an image
func (c *ImageApiController) ImageBuild(w http.ResponseWriter, r *http.Request) { 
	query := r.URL.Query()
	dockerfile := query.Get("dockerfile")
	t := query.Get("t")
	extrahosts := query.Get("extrahosts")
	remote := query.Get("remote")
	q := query.Get("q")
	nocache := query.Get("nocache")
	cachefrom := query.Get("cachefrom")
	pull := query.Get("pull")
	rm := query.Get("rm")
	forcerm := query.Get("forcerm")
	memory, err := parseInt32Parameter(query.Get("memory"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	memswap, err := parseInt32Parameter(query.Get("memswap"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	cpushares, err := parseInt32Parameter(query.Get("cpushares"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	cpusetcpus := query.Get("cpusetcpus")
	cpuperiod, err := parseInt32Parameter(query.Get("cpuperiod"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	cpuquota, err := parseInt32Parameter(query.Get("cpuquota"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	buildargs := query.Get("buildargs")
	shmsize, err := parseInt32Parameter(query.Get("shmsize"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	squash := query.Get("squash")
	labels := query.Get("labels")
	networkmode := query.Get("networkmode")
	contentType := r.Header.Get("Content-type")
	xRegistryConfig := r.Header.Get("X-Registry-Config")
	platform := query.Get("platform")
	target := query.Get("target")
	outputs := query.Get("outputs")
	inputStream := &*os.File{}
	if err := json.NewDecoder(r.Body).Decode(&inputStream); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	result, err := c.service.ImageBuild(r.Context(), dockerfile, t, extrahosts, remote, q, nocache, cachefrom, pull, rm, forcerm, memory, memswap, cpushares, cpusetcpus, cpuperiod, cpuquota, buildargs, shmsize, squash, labels, networkmode, contentType, xRegistryConfig, platform, target, outputs, *inputStream)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ImageCommit - Create a new image from a container
func (c *ImageApiController) ImageCommit(w http.ResponseWriter, r *http.Request) { 
	query := r.URL.Query()
	container := query.Get("container")
	repo := query.Get("repo")
	tag := query.Get("tag")
	comment := query.Get("comment")
	author := query.Get("author")
	pause := query.Get("pause")
	changes := query.Get("changes")
	containerConfig := &ContainerConfig{}
	if err := json.NewDecoder(r.Body).Decode(&containerConfig); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	result, err := c.service.ImageCommit(r.Context(), container, repo, tag, comment, author, pause, changes, *containerConfig)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ImageCreate - Create an image
func (c *ImageApiController) ImageCreate(w http.ResponseWriter, r *http.Request) { 
	query := r.URL.Query()
	fromImage := query.Get("fromImage")
	fromSrc := query.Get("fromSrc")
	repo := query.Get("repo")
	tag := query.Get("tag")
	message := query.Get("message")
	xRegistryAuth := r.Header.Get("X-Registry-Auth")
	platform := query.Get("platform")
	inputImage := &string{}
	if err := json.NewDecoder(r.Body).Decode(&inputImage); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	result, err := c.service.ImageCreate(r.Context(), fromImage, fromSrc, repo, tag, message, xRegistryAuth, platform, *inputImage)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ImageDelete - Remove an image
func (c *ImageApiController) ImageDelete(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	name := params["name"]
	force := query.Get("force")
	noprune := query.Get("noprune")
	result, err := c.service.ImageDelete(r.Context(), name, force, noprune)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ImageGet - Export an image
func (c *ImageApiController) ImageGet(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	name := params["name"]
	result, err := c.service.ImageGet(r.Context(), name)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ImageGetAll - Export several images
func (c *ImageApiController) ImageGetAll(w http.ResponseWriter, r *http.Request) { 
	query := r.URL.Query()
	names := strings.Split(query.Get("names"), ",")
	result, err := c.service.ImageGetAll(r.Context(), names)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ImageHistory - Get the history of an image
func (c *ImageApiController) ImageHistory(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	name := params["name"]
	result, err := c.service.ImageHistory(r.Context(), name)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ImageInspect - Inspect an image
func (c *ImageApiController) ImageInspect(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	name := params["name"]
	result, err := c.service.ImageInspect(r.Context(), name)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ImageList - List Images
func (c *ImageApiController) ImageList(w http.ResponseWriter, r *http.Request) { 
	query := r.URL.Query()
	all := query.Get("all")
	filters := query.Get("filters")
	digests := query.Get("digests")
	result, err := c.service.ImageList(r.Context(), all, filters, digests)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ImageLoad - Import images
func (c *ImageApiController) ImageLoad(w http.ResponseWriter, r *http.Request) { 
	query := r.URL.Query()
	quiet := query.Get("quiet")
	imagesTarball := &*os.File{}
	if err := json.NewDecoder(r.Body).Decode(&imagesTarball); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	result, err := c.service.ImageLoad(r.Context(), quiet, *imagesTarball)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ImagePrune - Delete unused images
func (c *ImageApiController) ImagePrune(w http.ResponseWriter, r *http.Request) { 
	query := r.URL.Query()
	filters := query.Get("filters")
	result, err := c.service.ImagePrune(r.Context(), filters)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ImagePush - Push an image
func (c *ImageApiController) ImagePush(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	name := params["name"]
	xRegistryAuth := r.Header.Get("X-Registry-Auth")
	tag := query.Get("tag")
	result, err := c.service.ImagePush(r.Context(), name, xRegistryAuth, tag)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ImageSearch - Search images
func (c *ImageApiController) ImageSearch(w http.ResponseWriter, r *http.Request) { 
	query := r.URL.Query()
	term := query.Get("term")
	limit, err := parseInt32Parameter(query.Get("limit"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	filters := query.Get("filters")
	result, err := c.service.ImageSearch(r.Context(), term, limit, filters)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ImageTag - Tag an image
func (c *ImageApiController) ImageTag(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	name := params["name"]
	repo := query.Get("repo")
	tag := query.Get("tag")
	result, err := c.service.ImageTag(r.Context(), name, repo, tag)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}
