/*
 * Docker Engine API
 *
 * The Engine API is an HTTP API served by Docker Engine. It is the API the Docker client uses to communicate with the Engine, so everything the Docker client can do can be done with the API.  Most of the client's commands map directly to API endpoints (e.g. `docker ps` is `GET /containers/json`). The notable exception is running containers, which consists of several API calls.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```  # Versioning  The API is usually changed in each release, so API calls are versioned to ensure that clients don't break. To lock to a specific version of the API, you prefix the URL with its version, for example, call `/v1.30/info` to use the v1.30 version of the `/info` endpoint. If the API version specified in the URL is not supported by the daemon, a HTTP `400 Bad Request` error message is returned.  If you omit the version-prefix, the current version of the API (v1.41) is used. For example, calling `/info` is the same as calling `/v1.41/info`. Using the API without a version-prefix is deprecated and will be removed in a future release.  Engine releases in the near future should support this version of the API, so your client will continue to work even if it is talking to a newer Engine.  The API uses an open schema model, which means server may add extra properties to responses. Likewise, the server will ignore any extra query parameters and request body properties. When you write clients, you need to ignore additional properties in responses to ensure they do not break when talking to newer daemons.   # Authentication  Authentication for registries is handled client side. The client has to send authentication details to various endpoints that need to communicate with registries, such as `POST /images/(name)/push`. These are sent as `X-Registry-Auth` header as a [base64url encoded](https://tools.ietf.org/html/rfc4648#section-5) (JSON) string with the following structure:  ``` {   \"username\": \"string\",   \"password\": \"string\",   \"email\": \"string\",   \"serveraddress\": \"string\" } ```  The `serveraddress` is a domain/IP without a protocol. Throughout this structure, double quotes are required.  If you have already got an identity token from the [`/auth` endpoint](#operation/SystemAuth), you can just pass this instead of credentials:  ``` {   \"identitytoken\": \"9cbaf023786cd7...\" } ``` 
 *
 * API version: 1.41
 * Generated by: api Generator (https://api-generator.tech)
 */

package api

import (
	"encoding/json"
	"net/http"
	"os"
	"strings"

	"github.com/gorilla/mux"
)

// A ContainerApiController binds http requests to an api service and writes the service results to the http response
type ContainerApiController struct {
	service ContainerApiServicer
}

// NewContainerApiController creates a default api controller
func NewContainerApiController(s ContainerApiServicer) Router {
	return &ContainerApiController{ service: s }
}

// Routes returns all of the api route for the ContainerApiController
func (c *ContainerApiController) Routes() Routes {
	return Routes{ 
		{
			"ContainerArchive",
			strings.ToUpper("Get"),
			"/v1.41/containers/{id}/archive",
			c.ContainerArchive,
		},
		{
			"ContainerArchiveInfo",
			strings.ToUpper("Head"),
			"/v1.41/containers/{id}/archive",
			c.ContainerArchiveInfo,
		},
		{
			"ContainerAttach",
			strings.ToUpper("Post"),
			"/v1.41/containers/{id}/attach",
			c.ContainerAttach,
		},
		{
			"ContainerAttachWebsocket",
			strings.ToUpper("Get"),
			"/v1.41/containers/{id}/attach/ws",
			c.ContainerAttachWebsocket,
		},
		{
			"ContainerChanges",
			strings.ToUpper("Get"),
			"/v1.41/containers/{id}/changes",
			c.ContainerChanges,
		},
		{
			"ContainerCreate",
			strings.ToUpper("Post"),
			"/v1.41/containers/create",
			c.ContainerCreate,
		},
		{
			"ContainerDelete",
			strings.ToUpper("Delete"),
			"/v1.41/containers/{id}",
			c.ContainerDelete,
		},
		{
			"ContainerExport",
			strings.ToUpper("Get"),
			"/v1.41/containers/{id}/export",
			c.ContainerExport,
		},
		{
			"ContainerInspect",
			strings.ToUpper("Get"),
			"/v1.41/containers/{id}/json",
			c.ContainerInspect,
		},
		{
			"ContainerKill",
			strings.ToUpper("Post"),
			"/v1.41/containers/{id}/kill",
			c.ContainerKill,
		},
		{
			"ContainerList",
			strings.ToUpper("Get"),
			"/v1.41/containers/json",
			c.ContainerList,
		},
		{
			"ContainerLogs",
			strings.ToUpper("Get"),
			"/v1.41/containers/{id}/logs",
			c.ContainerLogs,
		},
		{
			"ContainerPause",
			strings.ToUpper("Post"),
			"/v1.41/containers/{id}/pause",
			c.ContainerPause,
		},
		{
			"ContainerPrune",
			strings.ToUpper("Post"),
			"/v1.41/containers/prune",
			c.ContainerPrune,
		},
		{
			"ContainerRename",
			strings.ToUpper("Post"),
			"/v1.41/containers/{id}/rename",
			c.ContainerRename,
		},
		{
			"ContainerResize",
			strings.ToUpper("Post"),
			"/v1.41/containers/{id}/resize",
			c.ContainerResize,
		},
		{
			"ContainerRestart",
			strings.ToUpper("Post"),
			"/v1.41/containers/{id}/restart",
			c.ContainerRestart,
		},
		{
			"ContainerStart",
			strings.ToUpper("Post"),
			"/v1.41/containers/{id}/start",
			c.ContainerStart,
		},
		{
			"ContainerStats",
			strings.ToUpper("Get"),
			"/v1.41/containers/{id}/stats",
			c.ContainerStats,
		},
		{
			"ContainerStop",
			strings.ToUpper("Post"),
			"/v1.41/containers/{id}/stop",
			c.ContainerStop,
		},
		{
			"ContainerTop",
			strings.ToUpper("Get"),
			"/v1.41/containers/{id}/top",
			c.ContainerTop,
		},
		{
			"ContainerUnpause",
			strings.ToUpper("Post"),
			"/v1.41/containers/{id}/unpause",
			c.ContainerUnpause,
		},
		{
			"ContainerUpdate",
			strings.ToUpper("Post"),
			"/v1.41/containers/{id}/update",
			c.ContainerUpdate,
		},
		{
			"ContainerWait",
			strings.ToUpper("Post"),
			"/v1.41/containers/{id}/wait",
			c.ContainerWait,
		},
		{
			"PutContainerArchive",
			strings.ToUpper("Put"),
			"/v1.41/containers/{id}/archive",
			c.PutContainerArchive,
		},
	}
}

// ContainerArchive - Get an archive of a filesystem resource in a container
func (c *ContainerApiController) ContainerArchive(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	path := query.Get("path")
	result, err := c.service.ContainerArchive(r.Context(), id, path)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerArchiveInfo - Get information about files in a container
func (c *ContainerApiController) ContainerArchiveInfo(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	path := query.Get("path")
	result, err := c.service.ContainerArchiveInfo(r.Context(), id, path)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerAttach - Attach to a container
func (c *ContainerApiController) ContainerAttach(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	detachKeys := query.Get("detachKeys")
	logs := query.Get("logs")
	stream := query.Get("stream")
	stdin := query.Get("stdin")
	stdout := query.Get("stdout")
	stderr := query.Get("stderr")
	result, err := c.service.ContainerAttach(r.Context(), id, detachKeys, logs, stream, stdin, stdout, stderr)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerAttachWebsocket - Attach to a container via a websocket
func (c *ContainerApiController) ContainerAttachWebsocket(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	detachKeys := query.Get("detachKeys")
	logs := query.Get("logs")
	stream := query.Get("stream")
	stdin := query.Get("stdin")
	stdout := query.Get("stdout")
	stderr := query.Get("stderr")
	result, err := c.service.ContainerAttachWebsocket(r.Context(), id, detachKeys, logs, stream, stdin, stdout, stderr)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerChanges - Get changes on a container’s filesystem
func (c *ContainerApiController) ContainerChanges(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	id := params["id"]
	result, err := c.service.ContainerChanges(r.Context(), id)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerCreate - Create a container
func (c *ContainerApiController) ContainerCreate(w http.ResponseWriter, r *http.Request) { 
	query := r.URL.Query()
	body := &UNKNOWN_BASE_TYPE{}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	name := query.Get("name")
	result, err := c.service.ContainerCreate(r.Context(), *body, name)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerDelete - Remove a container
func (c *ContainerApiController) ContainerDelete(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	v := query.Get("v")
	force := query.Get("force")
	link := query.Get("link")
	result, err := c.service.ContainerDelete(r.Context(), id, v, force, link)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerExport - Export a container
func (c *ContainerApiController) ContainerExport(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	id := params["id"]
	result, err := c.service.ContainerExport(r.Context(), id)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerInspect - Inspect a container
func (c *ContainerApiController) ContainerInspect(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	size := query.Get("size")
	result, err := c.service.ContainerInspect(r.Context(), id, size)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerKill - Kill a container
func (c *ContainerApiController) ContainerKill(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	signal := query.Get("signal")
	result, err := c.service.ContainerKill(r.Context(), id, signal)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerList - List containers
func (c *ContainerApiController) ContainerList(w http.ResponseWriter, r *http.Request) { 
	query := r.URL.Query()
	all := query.Get("all")
	limit, err := parseInt32Parameter(query.Get("limit"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	size := query.Get("size")
	filters := query.Get("filters")
	result, err := c.service.ContainerList(r.Context(), all, limit, size, filters)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerLogs - Get container logs
func (c *ContainerApiController) ContainerLogs(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	follow := query.Get("follow")
	stdout := query.Get("stdout")
	stderr := query.Get("stderr")
	since, err := parseInt32Parameter(query.Get("since"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	until, err := parseInt32Parameter(query.Get("until"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	timestamps := query.Get("timestamps")
	tail := query.Get("tail")
	result, err := c.service.ContainerLogs(r.Context(), id, follow, stdout, stderr, since, until, timestamps, tail)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerPause - Pause a container
func (c *ContainerApiController) ContainerPause(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	id := params["id"]
	result, err := c.service.ContainerPause(r.Context(), id)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerPrune - Delete stopped containers
func (c *ContainerApiController) ContainerPrune(w http.ResponseWriter, r *http.Request) { 
	query := r.URL.Query()
	filters := query.Get("filters")
	result, err := c.service.ContainerPrune(r.Context(), filters)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerRename - Rename a container
func (c *ContainerApiController) ContainerRename(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	name := query.Get("name")
	result, err := c.service.ContainerRename(r.Context(), id, name)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerResize - Resize a container TTY
func (c *ContainerApiController) ContainerResize(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	h, err := parseInt32Parameter(query.Get("h"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	w, err := parseInt32Parameter(query.Get("w"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	result, err := c.service.ContainerResize(r.Context(), id, h, w)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerRestart - Restart a container
func (c *ContainerApiController) ContainerRestart(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	t, err := parseInt32Parameter(query.Get("t"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	result, err := c.service.ContainerRestart(r.Context(), id, t)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerStart - Start a container
func (c *ContainerApiController) ContainerStart(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	detachKeys := query.Get("detachKeys")
	result, err := c.service.ContainerStart(r.Context(), id, detachKeys)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerStats - Get container stats based on resource usage
func (c *ContainerApiController) ContainerStats(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	stream := query.Get("stream")
	oneShot := query.Get("one-shot")
	result, err := c.service.ContainerStats(r.Context(), id, stream, oneShot)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerStop - Stop a container
func (c *ContainerApiController) ContainerStop(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	t, err := parseInt32Parameter(query.Get("t"))
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	result, err := c.service.ContainerStop(r.Context(), id, t)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerTop - List processes running inside a container
func (c *ContainerApiController) ContainerTop(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	psArgs := query.Get("ps_args")
	result, err := c.service.ContainerTop(r.Context(), id, psArgs)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerUnpause - Unpause a container
func (c *ContainerApiController) ContainerUnpause(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	id := params["id"]
	result, err := c.service.ContainerUnpause(r.Context(), id)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerUpdate - Update a container
func (c *ContainerApiController) ContainerUpdate(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	id := params["id"]
	update := &UNKNOWN_BASE_TYPE{}
	if err := json.NewDecoder(r.Body).Decode(&update); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	result, err := c.service.ContainerUpdate(r.Context(), id, *update)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ContainerWait - Wait for a container
func (c *ContainerApiController) ContainerWait(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	condition := query.Get("condition")
	result, err := c.service.ContainerWait(r.Context(), id, condition)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// PutContainerArchive - Extract an archive of files or folders to a directory in a container
func (c *ContainerApiController) PutContainerArchive(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	query := r.URL.Query()
	id := params["id"]
	path := query.Get("path")
	inputStream := &*os.File{}
	if err := json.NewDecoder(r.Body).Decode(&inputStream); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	noOverwriteDirNonDir := query.Get("noOverwriteDirNonDir")
	copyUIDGID := query.Get("copyUIDGID")
	result, err := c.service.PutContainerArchive(r.Context(), id, path, *inputStream, noOverwriteDirNonDir, copyUIDGID)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}
