/*
 * Docker Engine API
 *
 * The Engine API is an HTTP API served by Docker Engine. It is the API the Docker client uses to communicate with the Engine, so everything the Docker client can do can be done with the API.  Most of the client's commands map directly to API endpoints (e.g. `docker ps` is `GET /containers/json`). The notable exception is running containers, which consists of several API calls.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```  # Versioning  The API is usually changed in each release, so API calls are versioned to ensure that clients don't break. To lock to a specific version of the API, you prefix the URL with its version, for example, call `/v1.30/info` to use the v1.30 version of the `/info` endpoint. If the API version specified in the URL is not supported by the daemon, a HTTP `400 Bad Request` error message is returned.  If you omit the version-prefix, the current version of the API (v1.41) is used. For example, calling `/info` is the same as calling `/v1.41/info`. Using the API without a version-prefix is deprecated and will be removed in a future release.  Engine releases in the near future should support this version of the API, so your client will continue to work even if it is talking to a newer Engine.  The API uses an open schema model, which means server may add extra properties to responses. Likewise, the server will ignore any extra query parameters and request body properties. When you write clients, you need to ignore additional properties in responses to ensure they do not break when talking to newer daemons.   # Authentication  Authentication for registries is handled client side. The client has to send authentication details to various endpoints that need to communicate with registries, such as `POST /images/(name)/push`. These are sent as `X-Registry-Auth` header as a [base64url encoded](https://tools.ietf.org/html/rfc4648#section-5) (JSON) string with the following structure:  ``` {   \"username\": \"string\",   \"password\": \"string\",   \"email\": \"string\",   \"serveraddress\": \"string\" } ```  The `serveraddress` is a domain/IP without a protocol. Throughout this structure, double quotes are required.  If you have already got an identity token from the [`/auth` endpoint](#operation/SystemAuth), you can just pass this instead of credentials:  ``` {   \"identitytoken\": \"9cbaf023786cd7...\" } ``` 
 *
 * API version: 1.41
 * Generated by: api Generator (https://api-generator.tech)
 */

package api

import (
	"context"
	"net/http"
	"errors"
	"os"
)

// ImageApiService is a service that implents the logic for the ImageApiServicer
// This service should implement the business logic for every endpoint for the ImageApi API. 
// Include any external packages or services that will be required by this service.
type ImageApiService struct {
}

// NewImageApiService creates a default api service
func NewImageApiService() ImageApiServicer {
	return &ImageApiService{}
}

// BuildPrune - Delete builder cache
func (s *ImageApiService) BuildPrune(ctx context.Context, keepStorage int64, all bool, filters string) (ImplResponse, error) {
	// TODO - update BuildPrune with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, BuildPruneResponse{}) or use other options such as http.Ok ...
	//return Response(200, BuildPruneResponse{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("BuildPrune method not implemented")
}

// ImageBuild - Build an image
func (s *ImageApiService) ImageBuild(ctx context.Context, dockerfile string, t string, extrahosts string, remote string, q bool, nocache bool, cachefrom string, pull string, rm bool, forcerm bool, memory int32, memswap int32, cpushares int32, cpusetcpus string, cpuperiod int32, cpuquota int32, buildargs string, shmsize int32, squash bool, labels string, networkmode string, contentType string, xRegistryConfig string, platform string, target string, outputs string, inputStream *os.File) (ImplResponse, error) {
	// TODO - update ImageBuild with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImageBuild method not implemented")
}

// ImageCommit - Create a new image from a container
func (s *ImageApiService) ImageCommit(ctx context.Context, container string, repo string, tag string, comment string, author string, pause bool, changes string, containerConfig ContainerConfig) (ImplResponse, error) {
	// TODO - update ImageCommit with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, IdResponse{}) or use other options such as http.Ok ...
	//return Response(201, IdResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImageCommit method not implemented")
}

// ImageCreate - Create an image
func (s *ImageApiService) ImageCreate(ctx context.Context, fromImage string, fromSrc string, repo string, tag string, message string, xRegistryAuth string, platform string, inputImage string) (ImplResponse, error) {
	// TODO - update ImageCreate with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImageCreate method not implemented")
}

// ImageDelete - Remove an image
func (s *ImageApiService) ImageDelete(ctx context.Context, name string, force bool, noprune bool) (ImplResponse, error) {
	// TODO - update ImageDelete with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []ImageDeleteResponseItem{}) or use other options such as http.Ok ...
	//return Response(200, []ImageDeleteResponseItem{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(409, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(409, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImageDelete method not implemented")
}

// ImageGet - Export an image
func (s *ImageApiService) ImageGet(ctx context.Context, name string) (ImplResponse, error) {
	// TODO - update ImageGet with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, *os.File{}) or use other options such as http.Ok ...
	//return Response(200, *os.File{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImageGet method not implemented")
}

// ImageGetAll - Export several images
func (s *ImageApiService) ImageGetAll(ctx context.Context, names []string) (ImplResponse, error) {
	// TODO - update ImageGetAll with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, *os.File{}) or use other options such as http.Ok ...
	//return Response(200, *os.File{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImageGetAll method not implemented")
}

// ImageHistory - Get the history of an image
func (s *ImageApiService) ImageHistory(ctx context.Context, name string) (ImplResponse, error) {
	// TODO - update ImageHistory with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []HistoryResponseItem{}) or use other options such as http.Ok ...
	//return Response(200, []HistoryResponseItem{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImageHistory method not implemented")
}

// ImageInspect - Inspect an image
func (s *ImageApiService) ImageInspect(ctx context.Context, name string) (ImplResponse, error) {
	// TODO - update ImageInspect with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Image{}) or use other options such as http.Ok ...
	//return Response(200, Image{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImageInspect method not implemented")
}

// ImageList - List Images
func (s *ImageApiService) ImageList(ctx context.Context, all bool, filters string, digests bool) (ImplResponse, error) {
	// TODO - update ImageList with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []ImageSummary{}) or use other options such as http.Ok ...
	//return Response(200, []ImageSummary{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImageList method not implemented")
}

// ImageLoad - Import images
func (s *ImageApiService) ImageLoad(ctx context.Context, quiet bool, imagesTarball *os.File) (ImplResponse, error) {
	// TODO - update ImageLoad with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImageLoad method not implemented")
}

// ImagePrune - Delete unused images
func (s *ImageApiService) ImagePrune(ctx context.Context, filters string) (ImplResponse, error) {
	// TODO - update ImagePrune with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ImagePruneResponse{}) or use other options such as http.Ok ...
	//return Response(200, ImagePruneResponse{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImagePrune method not implemented")
}

// ImagePush - Push an image
func (s *ImageApiService) ImagePush(ctx context.Context, name string, xRegistryAuth string, tag string) (ImplResponse, error) {
	// TODO - update ImagePush with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImagePush method not implemented")
}

// ImageSearch - Search images
func (s *ImageApiService) ImageSearch(ctx context.Context, term string, limit int32, filters string) (ImplResponse, error) {
	// TODO - update ImageSearch with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []ImageSearchResponseItem{}) or use other options such as http.Ok ...
	//return Response(200, []ImageSearchResponseItem{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImageSearch method not implemented")
}

// ImageTag - Tag an image
func (s *ImageApiService) ImageTag(ctx context.Context, name string, repo string, tag string) (ImplResponse, error) {
	// TODO - update ImageTag with the required logic for this service method.
	// Add api_image_service.api to the .api-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	//return Response(201, nil),nil

	//TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(404, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(409, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(409, ErrorResponse{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorResponse{}) or use other options such as http.Ok ...
	//return Response(500, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImageTag method not implemented")
}

